name: Backend Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "backend/**"
      - "docker-compose.yml"
      - ".github/workflows/backend-deploy.yml"

permissions:
  contents: read

jobs:
  deploy-backend:
    runs-on: ubuntu-local
    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          password: ${{ secrets.DEPLOY_PASSWORD }}
          script: |
            cd ${{ vars.BACKEND_PATH }}
            git remote set-url origin https://git.unself.top/Handy_Wote/pinf.git
            git pull origin main
            docker compose up -d --build